{% set name = "mplhep_data" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd1f3ad3af9dbff33aef9e7406d2130d624a0bd1d5aa5970fc713a6421165a4e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7

test:
  imports:
    - mplhep_data
  commands:
    - pip check
    - pip show mplhep_data | grep "{{ version }}"
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/mplhep_data
  license: MIT AND OFL-1.1 AND LPPL-1.3c
  license_file:
    - LICENSE
    - src/mplhep_data/fonts/firasans/LICENSE_FiraSans
    - src/mplhep_data/fonts/firamath/LICENSE_FiraMath
    - src/mplhep_data/fonts/texgyreheros/LICENSE_TexGyreHeros
  summary: Data sub-package for mplhep
  dev_url: https://github.com/scikit-hep/mplhep_data

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - andrzejnovak
    - chrisburr
